# CitizenSpace Supabase Configuration
# Generated: 2025-09-29

[project]
name = "CitizenSpace"
id = "your-project-ref"

[api]
port = 54321
schemas = ["public"]
extra_search_path = ["public"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[studio]
port = 54323

[inbucket]
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
file_size_limit = "50MiB"

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://citizenspace.com"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[auth.external.google]
enabled = false
client_id = ""
secret = ""

[auth.external.github]
enabled = false
client_id = ""
secret = ""

# Rate limiting configuration
[auth.rate_limits]
email_signup = 10
email_login = 20
sms_signup = 5
sms_login = 10

# Database migrations
[db.migrations]
auto_run = false
path = "./migrations"

# Local development settings
[local]
host = "localhost"
port = 54321